sudo: false
language: c
cache: ccache
script:
#
# Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
#

#
# Toolchain Choice
# This will clone TeamVee Prebuilt Toolchains in directory described in build.sh
#
# Branchs available is:
# Google Branch is "google_gcc" | (1) 4.7 / (2) 4.8
# Linaro Branch is "linaro_gcc" | (1) 4.8.4 / (2) 4.9.4

# Toolchain branch select here is Google 4.7
- export ntoolchainbranch="google_gcc"
- git clone -b "${ntoolchainbranch}" "https://github.com/TeamVee/android_prebuilt_toolchains" "../android_prebuilt_toolchains"

# ${ntoolchainchoice} is your Toolchain Choice
- export ntoolchainchoice="1"

# ${ntoolchain}
# "4" is "Toolchain Choice"
- ntoolchain="4${ntoolchainchoice}"

# ${ndevice}
# "2" is "Clean Kernel"
# "3" is "Device Choice"
- ndevice="23"

# ${ndevicechoice} is "Number of Choice under Device Choice"
# - export ndevicechoice="#"

# ${nbuild}
# "6" is "Build Kernel"
# "7" is "Zip the kernel and Modules"
# "q" is to Exit of Script
- nbuild="67q"

# Main variables
# Call of 'build.sh'
# - source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"

# Export of zipfile to deploy
# - export zipfile#="${zipfile}"

# TravisCI Custom Patches
- git apply zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch

# Build for Samsung Core 2 | SM-G355H SM-G355HN SM-G355M
- export ndevicechoice="1"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
- export zipfile1="${zipfile}"
- export ndevicechoice="2"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
- export zipfile2="${zipfile}"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "kP0p3Knq37VXkPk1wTZv2cx+4zoslHrVRBW572JC7X7MpBlI/6Qbjkw2xIio00zeXHI7GLQrsxI+IwavAQ0c9kEzOse63A1b6nqvhggWrunSCWt5xgAdtFYaJwPCgq1029nTXcITezrlL+QHOc5QfYXFyHPfZ78tdkJOBPhFHsZ4cVT0jGjq8FiWOTiD9htd0FhFmp8+hcqeot2u4aeuEcfmVjGe5ISRV4svNy+ka48+vBFL/jRioRwBPaufsDlkWlPCn/DTbqUnhBfktaWJDpi2Suve+xvSWOY6/8SA5XYXEeSBy8GVTvGRElE8xeXMC1UhHL0EEGYoFLNfqOz8P/QQB2ZXkZCTJd82pM/RcSb6NPxUFYyrc+eTf2n0DCQFX3Dhkzso4ElGVI8+PIyf9u5Mke5AD1zL/VMvtYiNO6ZoeijiB3Hx3A2zpr4UpECgr52v/nPVJ397qcBRyuvTOQuJh4HDrCvpliuzooFUJG5WQ2cs4Qsgy/u8r1PuwpQQ0DFiNH8EQ3PKZ2K/jBYZwOAecl+3apo91nW3cQNIg9xEZcVOxwW2HE48IzCpvO+17FpS9HHp2H9JwHd0tenfJy35t4Dd7P7TuBJ+RymGtn0OoNVrFyN4IuPZmmW4Ypu0aLsKqvk0sgKJyWxfu/CKKZoOOV9Up38+J9on1HKmCVA="
  file:
    - "zip-creator/${zipfile1}"
    - "zip-creator/${zipfile2}"
  on:
    tags: true
