sudo: required
language: c
cache: ccache
script:
#
# Travis CI Script by Caio Oliveira aka Caio99BR <caiooliveirafarias0@gmail.com>
#

#
# Toolchain Choice
# This will clone TeamVee Prebuilt Toolchains in directory described in build.sh
#
# Branchs available is:
# Google Branch is "google_gcc" | (1) 4.7 / (2) 4.8
# Linaro Branch is "linaro_gcc" | (1) 4.8.4 / (2) 4.9.4

# Toolchain branch select here is Google 4.7
- export ntoolchainbranch="google_gcc"
- git clone -b "${ntoolchainbranch}" "https://github.com/TeamVee/android_prebuilt_toolchains" "../android_prebuilt_toolchains"

# ${ntoolchainchoice} is your Toolchain Choice
- export ntoolchainchoice="1"

# ${ntoolchain}
# "4" is "Toolchain Choice"
- ntoolchain="4${ntoolchainchoice}"

# ${ndevice}
# "2" is "Clean Kernel"
# "3" is "Device Choice"
- ndevice="23"

# ${ndevicechoice} is "Number of Choice under Device Choice"
# - export ndevicechoice="#"

# ${nbuild}
# "6" is "Build Kernel"
# "7" is "Zip the kernel and Modules"
# "q" is to Exit of Script
- nbuild="67q"

# Main variables
# Call of 'build.sh'
# - source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"

# Export of zipfile to deploy
# - export zipfile#="${zipfile}"

# TravisCI Custom Patches
- patch -p1 < zip-creator/travis-ci/0001-TravisCI-Custom-Patches.patch

# Build for Samsung Core 2 | SM-G355H SM-G355HN SM-G355M
- export ndevicechoice="1"
- source build.sh <<< "${ndevice}${ndevicechoice}${ntoolchain}${nbuild}"
- export zipfile1="${zipfile}"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "Ff2z8V191nLZoQoYKoDzGbvwZuYBkupyXpLfcc79MTbu0k3qbeMw6J+UqIWMPDcEiRTGT6FP53JRE8A+c0yiTlZakagE9hfK0f0nF5sIIdUvbMLm6yR6K6GFM9n1G3d8NWFve8bz5Z3zBt4cl2ehkv414SzxsvMKRLYshnApGRt69e//d07ldLKlbSBd6UG5qWNex5aUjV4/KcLJC6UQfvbW1CekTIS+Ck+8Q/fnUGlMXcUDOC3A+XImzuWBDdnEOphHQrwVvjlAgdazeXFc+Ycus5pHDpQ47BXjdOaegg1CeqD106qKDjG1YRLDntL74lckSZy5I19Njp3ic6OKSfKct8HdD1DU1KbwYMVAVqxxjzEBuyjEJ97ymMTeSI4IDoVx6LKDSOPfJrSU4kKiRNvhwB/8EMcH1E8pMAyHaM6h07aWIIdeLE87mUSwClW9OrRhcS1XBNn8pmDO7a4yLhLCxczRAo5vhGhWL2TxTJ2QbxNKXypdbN0Toz4nm1c/zi6QKqZxvww7+ZjG6hIL8+n1SfX9G+9LH9WA206ziDdYESMrV3XU/X4LMCPmmO+1Rks5GShyNvfuic7m8y2uiTY/PVLcIS83HcKwE8CMDIa0v6pA00Bj+LXOIKg3KDjlxhogE3swlDINHVqvPxY+QQEN4SJcx/2VlTKe5k6ReUw="
  file:
    - "zip-creator/${zipfile1}"
    - "zip-creator/${zipfile2}"
  on:
    tags: true
